name: CI Pipeline
on:
  push:
    branches: ["main"]
jobs:
  deploy-movie-api:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Create Systemd Service File
        run: |
          # Create a systemd service file for the movie recommendation API
          sudo tee /etc/systemd/system/movie-rec-api.service << EOL
          [Unit]
          Description=Movie Recommendation API
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/movie-rec-v2/movie.api
          Environment="PATH=/home/ubuntu/.venv/bin"
          ExecStart=/home/ubuntu/.venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target
          EOL

      - name: Deploy Movie API
        run: |
          # Navigate to the project directory
          cd /home/ubuntu/movie-rec-v2/movie.api
          
          # Activate virtual environment and update requirements
          source /home/ubuntu/.venv/bin/activate
          git pull
          pip install -r requirements.txt
          
          # Reload systemd, restart the service
          sudo systemctl daemon-reload
          sudo systemctl restart movie-rec-api
          sudo systemctl enable movie-rec-api
          
          # Optional: Check service status
          sudo systemctl status movie-rec-api
